on:
    workflow_dispatch:

jobs:
  sign_local_object_keylessly_with_cosign:
    runs-on: ubuntu-latest

    permissions: 
        contents: write 
        id-token: write

    name: Install Cosign 
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Install Cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: 'v2.0.0-rc.0'
      - name: Sign with Github Identity 
        run: cosign sign-blob --yes --bundle verification.json README.md
      - name: Get Current Time  
        id: date 
        run: echo "::set-output name=date::$(date +'%H-%M-%S')" 
      - name: Create a Release for Verification 
        uses: ncipollo/release-action@v1
        with:
          artifacts: "README.md,verification.json"
          tag: release-${{ steps.date.outputs.date }}
          body: "verify the signature of the README.md file using ```cosign verify-blob --bundle verification.json --certificate-identity https://github.com/${{ github.workflow_ref}} --certificate-oidc-issuer https://token.actions.githubusercontent.com README.md```. " 
