on:
    workflow_dispatch:
    push:
        branches:
            -main
jobs:
  sign_local_object_keylessly_with_cosign:
    runs-on: ubuntu-latest

    permissions: 
        contents: read
        id-token: write

    name: Install Cosign and test presence in path
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Install Cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: 'v2.0.0-rc.0'
      - name: Sign with Github Identity 
        run: cosign sign-blob --yes README.md
